version: "3.8"

services:
  backend:
    depends_on:
      - database
    image: node:12-alpine
    working_dir: /app
    volumes:
      - type: bind
        source: .
        target: /app
    command: sh -c "yarn start:dev"
    ports:
      - 3000:3000
    env_file:
      - .env

  database:
    image: library/postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - database:/var/lib/postgresql
    env_file:
      - .env

volumes:
  database:
