version: "3.8"

services:
  backend:
    depends_on:
      - database
    build:
      context: .
    command: sh -c "yarn start:prod"
    expose:
      - 3000
    env_file:
      - .env

  database:
    image: library/postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - database:/var/lib/postgresql
    env_file:
      - .env

  nginx:
    image: nginx:latest
    restart: always
    entrypoint: nginx -g 'daemon off;'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    ports:
      - 80:80

volumes:
  database:
